export * from './qwikStart'
export { getMonths } from './utils/getMonths'
export { distributeData } from './utils/distributeData'
export type { PrecipitationValue } from './graphs/Precipitation'
export type { IceRulerValue } from './graphs/IceRuler'
