export * from './qwikStart'
export { getMonths, getMonthNumber } from './utils/getMonths'
export type { Months } from './utils/getMonths'
export { getDate } from './utils/getDate'
export { distributeData } from './utils/distributeData'
export type { PrecipitationValue } from './graphs/Precipitation'
export type { IceRulerValue } from './graphs/IceRuler'
